# Generated by Django 5.0.1 on 2024-04-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_rename_projects_project'),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
