# Generated by Django 5.0.6 on 2024-05-10 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Projects", "0006_alter_projectmembers_profile"),
        ("Tasks", "0003_task_created_at_alter_task_task_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project_members",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_member",
                to="Projects.projectmembers",
            ),
        ),
    ]
