# Generated by Django 5.0.4 on 2024-05-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_task_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_members',
            new_name='assigned_to',
        ),
    ]
