# Generated by Django 5.0.1 on 2024-05-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_rename_project_members_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TD', 'To-do'), ('IP', 'Inprogress'), ('CP', 'Completed')], default='TD', max_length=10),
        ),
    ]
