# Generated by Django 5.0.1 on 2024-05-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'To-do'), ('Progress', 'Inprogress'), ('Completed', 'Completed')], default='Todo', max_length=10),
        ),
    ]
