# Generated by Django 5.0.1 on 2024-05-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
