# Generated by Django 5.0.4 on 2024-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('IN', 'Intern'), ('AS', 'Associate'), ('MID', 'Mid-Senior'), ('LEAD', 'Lead'), ('DR', 'Director')], max_length=20),
        ),
    ]
