# Generated by Django 5.0.1 on 2024-04-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        ('Projects', '0001_initial'),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
