# Generated by Django 5.0.4 on 2024-05-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PL', 'Planned'), ('IP', 'In Progress'), ('OH', 'On Hold'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='PL', max_length=2),
        ),
    ]
