# Generated by Django 5.0.4 on 2024-05-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='project-icons/'),
        ),
    ]
