# Generated by Django 5.0.4 on 2024-05-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_project_icon'),
        ('Users', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_within_project', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_membership', to='Users.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_members', to='Projects.project')),
            ],
        ),
    ]
