# Generated by Django 5.0.4 on 2024-05-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_projectmembers'),
        ('Users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembers',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_membership', to='Users.userprofile'),
        ),
    ]
