# Generated by Django 5.0.4 on 2024-05-24 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_project_created_at'),
        ('Users', '0005_alter_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembers',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_membership', to='Users.userprofile'),
        ),
    ]
